"""fix courier wallet

Revision ID: 011a22eb6d7c
Revises: ef838c89326f
Create Date: 2026-04-23 00:24:36.033077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011a22eb6d7c'
down_revision: Union[str, Sequence[str], None] = 'ef838c89326f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier_wallets', 'pending_balance')
    op.drop_column('wallet_transactions', 'description')
    op.drop_column('wallet_transactions', 'type')
    op.drop_column('wallet_transactions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('wallet_transactions', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('wallet_transactions', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('courier_wallets', sa.Column('pending_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
