"""fix relationships

Revision ID: 05dc6ee8412c
Revises: e5240c4d46cf
Create Date: 2026-02-25 09:38:37.976788

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "05dc6ee8412c"
down_revision: Union[str, Sequence[str], None] = "e5240c4d46cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
