"""fix relationships

Revision ID: 0b3b43bf9516
Revises: 5a4c6c47e939
Create Date: 2026-02-25 09:48:13.781751

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0b3b43bf9516"
down_revision: Union[str, Sequence[str], None] = "5a4c6c47e939"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
