"""change

Revision ID: 13aa3b379b8b
Revises: 28e426245e82
Create Date: 2026-03-29 00:24:44.012283

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "13aa3b379b8b"
down_revision: Union[str, Sequence[str], None] = "28e426245e82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
