"""fix status in order

Revision ID: 200dc8901a9f
Revises: fc3546d8ffde
Create Date: 2026-04-14 20:59:49.939870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200dc8901a9f'
down_revision: Union[str, Sequence[str], None] = 'fc3546d8ffde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CREATED', 'ACCEPTED', 'COOKING', 'ON_THE_WAY', 'DELIVERED', 'CANCELED', name='orderstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('CREATED', 'ACCEPTED', 'COOKING', 'ON_THE_WAY', 'DELIVERED', 'CANCELED', name='orderstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    # ### end Alembic commands ###
