"""fix is_deleted

Revision ID: 319717a0f9f2
Revises: c8ae730e3d4e
Create Date: 2026-02-27 18:15:00.873325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "319717a0f9f2"
down_revision: Union[str, Sequence[str], None] = "c8ae730e3d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
