"""fix relationships

Revision ID: 3305d833bca8
Revises: ce7b31fb69f7
Create Date: 2026-02-25 09:20:17.574036

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3305d833bca8"
down_revision: Union[str, Sequence[str], None] = "ce7b31fb69f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
