"""add is_active in product

Revision ID: 453388e6cb5c
Revises: d9b7b3b8f23b
Create Date: 2026-03-07 19:41:11.683429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "453388e6cb5c"
down_revision: Union[str, Sequence[str], None] = "d9b7b3b8f23b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.alter_column(
        "products",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "price",
        existing_type=sa.BigInteger(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("products", "is_active")
    # ### end Alembic commands ###
