"""fix relationships

Revision ID: 5013a1f417f0
Revises: baf34fde8552
Create Date: 2026-02-25 09:25:50.546119

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "5013a1f417f0"
down_revision: Union[str, Sequence[str], None] = "baf34fde8552"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
