"""add: relation to disc table

Revision ID: 504e936f9fd6
Revises: b0fa0d473f61
Create Date: 2026-03-04 15:54:45.682724

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '504e936f9fd6'
down_revision: Union[str, Sequence[str], None] = 'b0fa0d473f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
