"""add: name field to notification table

Revision ID: 59aa33354f96
Revises: 517bb4656c7d
Create Date: 2026-03-03 11:31:29.548070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59aa33354f96"
down_revision: Union[str, Sequence[str], None] = "517bb4656c7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications", sa.Column("name", sa.String(length=100), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "name")
    # ### end Alembic commands ###
