"""fix relationships

Revision ID: 5a4c6c47e939
Revises: e015569533f9
Create Date: 2026-02-25 09:46:22.187403

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5a4c6c47e939"
down_revision: Union[str, Sequence[str], None] = "e015569533f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("deliveries_courier_id_fkey"), "deliveries", type_="foreignkey"
    )
    op.create_foreign_key(None, "deliveries", "couriers", ["courier_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "deliveries", type_="foreignkey")
    op.create_foreign_key(
        op.f("deliveries_courier_id_fkey"),
        "deliveries",
        "users",
        ["courier_id"],
        ["id"],
    )
    # ### end Alembic commands ###
