"""fix relationships

Revision ID: 636577314435
Revises: ecb8eb357660
Create Date: 2026-02-25 09:34:08.054768

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "636577314435"
down_revision: Union[str, Sequence[str], None] = "ecb8eb357660"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
