"""change

Revision ID: 75afdcd0e11c
Revises: 13aa3b379b8b
Create Date: 2026-03-29 00:27:57.465565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75afdcd0e11c"
down_revision: Union[str, Sequence[str], None] = "13aa3b379b8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("branches", sa.Column("latitude", sa.Float(), nullable=True))
    op.drop_column("branches", "lattitude")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "branches",
        sa.Column(
            "lattitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("branches", "latitude")
    # ### end Alembic commands ###
