"""new era

Revision ID: 9d077612a762
Revises: aa703800c42d
Create Date: 2026-03-04 14:32:50.330991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d077612a762'
down_revision: Union[str, Sequence[str], None] = 'aa703800c42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deliveries_courier_id_fkey'), 'deliveries', type_='foreignkey')
    op.drop_table('couriers')
    op.drop_table('discount_items')
    op.drop_table('discounts')
   
    
    op.create_foreign_key(None, 'deliveries', 'users', ['courier_id'], ['id'])
    # ### end Alembic commands ###
'''def upgrade():
    # Drop the foreign key FIRST before dropping couriers
    op.drop_constraint('deliveries_courier_id_fkey', 'deliveries', type_='foreignkey')
    
    op.drop_table('couriers')  # now this will work
    op.drop_table('discounts')
    op.drop_table('discount_items')
    # ... rest of the file unchanged'''

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('deliveries_courier_id_fkey'), 'deliveries', 'couriers', ['courier_id'], ['id'])
    op.create_table('discounts',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('discount_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('discounts_pkey'))
    )
    op.create_table('couriers',
    sa.Column('branch_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('couriers_branch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('couriers_pkey'))
    )
    op.create_table('discount_items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('discount_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], name=op.f('discount_items_discount_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('discount_items_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('discount_items_pkey'))
    )
    # ### end Alembic commands ###
