"""add: discount table

Revision ID: a578b5af5ebc
Revises: 9d077612a762
Create Date: 2026-03-04 15:04:03.084966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a578b5af5ebc'
down_revision: Union[str, Sequence[str], None] = '9d077612a762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deliveries', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('deliveries_courier_id_fkey'), 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'users', ['user_id'], ['id'])
    op.drop_column('deliveries', 'courier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('courier_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('deliveries_courier_id_fkey'), 'deliveries', 'users', ['courier_id'], ['id'])
    op.drop_column('deliveries', 'user_id')
    op.drop_table('discounts')
    # ### end Alembic commands ###
