"""add: some changes

Revision ID: b0fa0d473f61
Revises: a578b5af5ebc
Create Date: 2026-03-04 15:21:39.602436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0fa0d473f61"
down_revision: Union[str, Sequence[str], None] = "a578b5af5ebc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses", sa.Column("location_name", sa.String(length=100), nullable=True)
    )
    op.add_column("branches", sa.Column("lattitude", sa.Float(), nullable=True))
    op.add_column("branches", sa.Column("longitude", sa.Float(), nullable=True))
    op.add_column(
        "deliveries", sa.Column("courier_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint(
        op.f("deliveries_user_id_fkey"), "deliveries", type_="foreignkey"
    )
    op.create_foreign_key(None, "deliveries", "users", ["courier_id"], ["id"])
    op.drop_column("deliveries", "user_id")
    op.drop_column("notifications", "name")
    op.add_column("products", sa.Column("discount_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, "products", "discounts", ["discount_id"], ["id"])
    op.add_column("users", sa.Column("is_courier", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_courier")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "discount_id")
    op.add_column(
        "notifications",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "deliveries",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "deliveries", type_="foreignkey")
    op.create_foreign_key(
        op.f("deliveries_user_id_fkey"), "deliveries", "users", ["user_id"], ["id"]
    )
    op.drop_column("deliveries", "courier_id")
    op.drop_column("branches", "longitude")
    op.drop_column("branches", "lattitude")
    op.drop_column("addresses", "location_name")
    # ### end Alembic commands ###
