"""fix relationships

Revision ID: baf34fde8552
Revises: 3305d833bca8
Create Date: 2026-02-25 09:24:08.909512

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "baf34fde8552"
down_revision: Union[str, Sequence[str], None] = "3305d833bca8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
