"""fix delivery

Revision ID: c40d7954315c
Revises: ce722b9e13a3
Create Date: 2026-04-22 19:45:02.580066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40d7954315c'
down_revision: Union[str, Sequence[str], None] = 'ce722b9e13a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'courier_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'courier_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
