"""add:is_sent_to_all

Revision ID: c8ae730e3d4e
Revises: ee23fddb90d6
Create Date: 2026-02-26 20:41:02.763367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8ae730e3d4e"
down_revision: Union[str, Sequence[str], None] = "ee23fddb90d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications", sa.Column("is_sent_to_all", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "is_sent_to_all")
    # ### end Alembic commands ###
