"""fix relationships

Revision ID: ce7b31fb69f7
Revises: 869596818a50
Create Date: 2026-02-25 09:16:10.867675

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ce7b31fb69f7"
down_revision: Union[str, Sequence[str], None] = "869596818a50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
