"""changes  in promocode

Revision ID: d9b7b3b8f23b
Revises: 6f86a5bd7498
Create Date: 2026-03-06 12:11:34.089746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b7b3b8f23b'
down_revision: Union[str, Sequence[str], None] = '6f86a5bd7498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocodes', sa.Column('max_uses', sa.BigInteger(), nullable=True))
    op.add_column('promocodes', sa.Column('used_count', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promocodes', 'used_count')
    op.drop_column('promocodes', 'max_uses')
    # ### end Alembic commands ###
