"""fix relationships

Revision ID: e015569533f9
Revises: 05dc6ee8412c
Create Date: 2026-02-25 09:40:10.462818

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e015569533f9"
down_revision: Union[str, Sequence[str], None] = "05dc6ee8412c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
