"""fix user application

Revision ID: e458cdfc0840
Revises: 33fa969249d7
Create Date: 2026-04-16 12:32:23.275181

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e458cdfc0840"
down_revision: Union[str, Sequence[str], None] = "33fa969249d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
