"""fix relationships

Revision ID: e5240c4d46cf
Revises: 636577314435
Create Date: 2026-02-25 09:37:29.321876

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e5240c4d46cf"
down_revision: Union[str, Sequence[str], None] = "636577314435"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
