"""add is_active in product

Revision ID: e5f096c62945
Revises: 453388e6cb5c
Create Date: 2026-03-07 19:43:54.510400

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e5f096c62945"
down_revision: Union[str, Sequence[str], None] = "453388e6cb5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
