"""fix relationships

Revision ID: e9a84a59a328
Revises: 0b3b43bf9516
Create Date: 2026-02-25 11:34:26.061329

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e9a84a59a328"
down_revision: Union[str, Sequence[str], None] = "0b3b43bf9516"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
