"""fix relationships

Revision ID: ecb8eb357660
Revises: 5013a1f417f0
Create Date: 2026-02-25 09:32:02.276229

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ecb8eb357660"
down_revision: Union[str, Sequence[str], None] = "5013a1f417f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
