"""add asigned_at to delivery

Revision ID: ef838c89326f
Revises: c40d7954315c
Create Date: 2026-04-22 23:26:03.551200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef838c89326f'
down_revision: Union[str, Sequence[str], None] = 'c40d7954315c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('assigned_at', sa.DateTime(), nullable=True))    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'assigned_at')
    # ### end Alembic commands ###
