"""some changes

Revision ID: fc3546d8ffde
Revises: 5beb17480be6
Create Date: 2026-04-09 20:17:57.808614

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fc3546d8ffde"
down_revision: Union[str, Sequence[str], None] = "5beb17480be6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
